<?xml version="1.0" encoding="utf-8"?><Database Name="mytools" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ZHU-PC;Initial Catalog=mytools;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="mytoolsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.md5" Member="md5">
    <Type Name="md5">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="text1" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="text2" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ip" Type="System.String" DbType="Char(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserInfo" Member="UserInfo">
    <Type Name="UserInfo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sex" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="phone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Card" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="photo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="users_UserInfo" Member="users" ThisKey="userId" OtherKey="id" Type="users" IsForeignKey="true" />
      <Association Name="users_UserInfo1" Member="users1" ThisKey="username" OtherKey="username" Type="users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="users">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="signInTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="state" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="users_UserInfo" Member="UserInfo" ThisKey="id" OtherKey="userId" Type="UserInfo" />
      <Association Name="users_UserInfo1" Member="UserInfo1" ThisKey="username" OtherKey="username" Type="UserInfo" />
    </Type>
  </Table>
  <Table Name="dbo.show" Member="show">
    <Type Name="show">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="state" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="changeTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.report" Member="report">
    <Type Name="report">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="message1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="send_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ip" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IPdeny" Member="IPdeny">
    <Type Name="IPdeny">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ip" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="state" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="logindate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>